language: bash

sudo: false
dist: trusty

script:
  - export SHELLCHECK_OPTS="-e SC1091,SC1117"
  - shellcheck --version
  - shellcheck *.sh extras/*.sh

notifications:
  email:
    - linsongui@gmail.com
